import type {
  BudgetItem,
  ChecklistCategory,
  ChecklistCategoryKey,
  ChecklistItem,
  LocalizedText,
  ScheduleItem,
  WeddingData,
} from "@/types/wedding";

const lt = (ko: string, ja: string): LocalizedText => ({ ko, ja });

const categories: ChecklistCategory[] = [
  ["confirmed", "확정 일정", "確定日程"],
  ["photo", "촬영 준비", "前撮り準備"],
  ["ceremony", "본식 준비", "挙式準備"],
  ["sdm", "스드메", "スタジオ・ドレス・メイク"],
  ["attire", "예복/예물/한복", "礼服・指輪・韓服"],
  ["honeymoon", "허니문", "ハネムーン"],
  ["parents", "혼주 준비", "両家親準備"],
  ["invitation", "청첩장/부케/사회자", "招待状・ブーケ・司会"],
  ["home", "신혼집/가전/가구", "新居・家電・家具"],
  ["payment", "결제/포인트/캐시백", "支払い・ポイント・還元"],
  ["caution", "위약금/주의사항", "キャンセル料・注意事項"],
  ["planner", "플래너 문의 필요 항목", "プランナー確認事項"],
].map(([id, ko, ja]) => ({
  id: id as ChecklistCategoryKey,
  title: lt(ko, ja),
  description: lt(`${ko} 관련 준비 항목`, `${ja}に関する準備項目`),
}));

const item = (
  id: string,
  categoryId: ChecklistCategoryKey,
  ko: string,
  ja: string,
  options: Partial<ChecklistItem> = {},
): ChecklistItem => ({
  id,
  categoryId,
  title: lt(ko, ja),
  recommendedTiming: options.recommendedTiming || lt("일정에 맞춰 확인", "日程に合わせて確認"),
  ...options,
});

const checklist: ChecklistItem[] = [
  item("confirmed-photo-date", "confirmed", "웨딩촬영 일정 확인", "前撮り日程を確認", {
    deadline: "2026-06-07",
    important: true,
    recommendedTiming: lt("촬영 1개월 전까지", "撮影1か月前まで"),
  }),
  item("confirmed-photo-prep", "confirmed", "촬영 헤어메이크업 및 촬영가봉 일정 확인", "撮影ヘアメイク・仮縫い日程を確認", {
    deadline: "2026-06-07",
    important: true,
  }),
  item("confirmed-wedding-date", "confirmed", "예식 일정 확인", "挙式日程を確認", {
    deadline: "2026-11-01",
    important: true,
  }),
  item("confirmed-venue", "confirmed", "예식장 정보 확인", "式場情報を確認", {
    deadline: "2026-11-01",
    important: true,
    vendor: lt("스탠포드호텔코리아", "スタンフォードホテルコリア"),
  }),

  item("photo-dress-select", "photo", "촬영 드레스 셀렉 안내문 확인", "撮影ドレス選びの案内を確認", { deadline: "2026-05-31", important: true }),
  item("photo-prep-guide", "photo", "촬영 준비사항 확인", "撮影準備事項を確認", { deadline: "2026-06-07", important: true }),
  item("photo-groom-shirt", "photo", "촬영용 신랑 셔츠 준비", "撮影用新郎シャツを準備", { deadline: "2026-06-10" }),
  item("photo-groom-shoes", "photo", "촬영용 신랑 구두 준비", "撮影用新郎靴を準備", { deadline: "2026-06-10" }),
  item("photo-bowtie", "photo", "촬영용 보타이 준비", "撮影用蝶ネクタイを準備", { deadline: "2026-06-10" }),
  item("photo-tuxedo-rental", "photo", "촬영용 예복 또는 턱시도 대여 여부 결정", "撮影用礼服またはタキシードのレンタル可否を決定", { undecided: true, deadline: "2026-06-01" }),
  item("photo-ring-use", "photo", "커플링 촬영 활용 여부 결정", "ペアリングを撮影に使うか決定", { undecided: true }),
  item("photo-jewelry-consult", "photo", "예물 상담 필요 여부 결정", "結婚指輪相談の必要有無を決定", { undecided: true }),
  item("photo-hair-change", "photo", "촬영 헤어변형 진행 여부 결정", "撮影ヘアチェンジを行うか決定", { undecided: true, important: true }),
  item("photo-studio-hair-option", "photo", "스튜디오 자체 헤어변형 옵션 확인", "スタジオ内ヘアチェンジオプションを確認", { deadline: "2026-06-01" }),
  item("photo-happycall", "photo", "촬영 1~2주 전 해피콜 확인", "撮影1〜2週間前の確認連絡を確認", { deadline: "2026-06-07", important: true }),
  item("photo-helper-cash", "photo", "촬영 당일 헬퍼비 현금 준비", "撮影当日のヘルパー費用を現金で準備", { deadline: "2026-06-13", important: true }),
  item("photo-original-edit-cost", "photo", "원본+수정본 44만원 비용 확인", "原本＋修正版44万ウォン費用を確認", { deadline: "2026-06-14", important: true }),
  item("photo-original-delivery", "photo", "촬영 후 원본 수령 예상 시점 확인", "撮影後の原本受領予定時期を確認"),
  item("photo-album-delivery", "photo", "수정본/앨범/액자 수령 예상 시점 확인", "修正版・アルバム・額の受領予定時期を確認"),

  item("ceremony-dress-shop", "ceremony", "본식 드레스샵 확정", "挙式ドレスショップを確定", { deadline: "2026-09-30", important: true }),
  item("ceremony-makeup-shop", "ceremony", "본식 메이크업샵 확정", "挙式メイクショップを確定", { deadline: "2026-09-30", important: true }),
  item("ceremony-fitting-date", "ceremony", "본식가봉 일정 확정", "挙式ドレス仮縫い日程を確定", { deadline: "2026-10-31" }),
  item("ceremony-makeup-date", "ceremony", "본식헤메 일정 확정", "挙式ヘアメイク日程を確定", { deadline: "2026-10-31" }),
  item("ceremony-snap", "ceremony", "본식 스냅 진행 여부 결정", "挙式スナップ撮影の有無を決定", { undecided: true }),
  item("ceremony-dvd", "ceremony", "본식 DVD 진행 여부 결정", "挙式DVD撮影の有無を決定", { undecided: true }),
  item("ceremony-mc", "ceremony", "사회자 진행 여부 결정", "司会者の手配有無を決定", { undecided: true }),
  item("ceremony-song", "ceremony", "축가/연주 진행 여부 결정", "祝歌・演奏の有無を決定", { undecided: true }),
  item("ceremony-car", "ceremony", "웨딩카 진행 여부 결정", "ウェディングカーの有無を決定", { undecided: true }),
  item("ceremony-paebaek", "ceremony", "폐백 진행 여부 결정", "幣帛を行うか決定", { undecided: true }),
  item("ceremony-bouquet", "ceremony", "부케 준비", "ブーケを準備", { deadline: "2026-11-15" }),
  item("ceremony-meal-ticket", "ceremony", "식권 준비 체크", "食券準備を確認", { deadline: "2026-11-29" }),
  item("ceremony-flower-shower", "ceremony", "플라워샤워 준비 여부 체크", "フラワーシャワー準備有無を確認", { undecided: true }),
  item("ceremony-photo-table", "ceremony", "포토테이블 준비 여부 체크", "フォトテーブル準備有無を確認", { undecided: true }),

  item("sdm-photo-vendor", "sdm", "촬영 업체 셀럽비비 토탈 계약 내용 확인", "撮影業者Celeb Bibi Totalの契約内容を確認", { important: true }),
  item("sdm-dress-package", "sdm", "드레스샵 패키지 후보 비교", "ドレスショップ候補パッケージを比較", { undecided: true }),
  item("sdm-makeup-hiel", "sdm", "히엘 원장급 1회 포함 조건 확인", "Hiel院長級1回込み条件を確認", { important: true }),

  item("attire-groom-suit", "attire", "신랑 예복 상담", "新郎礼服相談", { undecided: true }),
  item("attire-tuxedo-rental", "attire", "촬영용 턱시도 대여 여부 확인", "撮影用タキシードレンタル有無を確認", { deadline: "2026-06-01" }),
  item("attire-shirt-bowtie-shoes", "attire", "셔츠/보타이/구두 준비", "シャツ・蝶ネクタイ・靴を準備", { deadline: "2026-06-10" }),
  item("attire-rings", "attire", "예물/커플링 상담", "結婚指輪・ペアリング相談", { undecided: true }),
  item("attire-ring-period", "attire", "커플링 제작 기간 확인", "ペアリング制作期間を確認", { undecided: true }),
  item("attire-parents-hanbok", "attire", "혼주 한복 상담", "両家親の韓服相談", { undecided: true }),
  item("attire-parents-suit", "attire", "혼주 정장 상담", "両家親のスーツ相談", { undecided: true }),
  item("attire-planner-booking", "attire", "제휴업체 이용 시 플래너 통해 예약했는지 확인", "提携業者利用時にプランナー経由予約か確認", { important: true }),
  item("attire-cashback-share", "attire", "캐시백 신청을 위해 플래너에게 방문일 공유", "還元申請のためプランナーへ訪問日を共有", { important: true }),

  item("honeymoon-region", "honeymoon", "허니문 지역 결정", "ハネムーン地域を決定", { undecided: true }),
  item("honeymoon-budget", "honeymoon", "예상 1인 예산 결정", "1人あたり予算を決定", { undecided: true }),
  item("honeymoon-date", "honeymoon", "출발 날짜 및 여행 기간 결정", "出発日と旅行期間を決定", { undecided: true }),
  item("honeymoon-agency", "honeymoon", "상담 희망 여행사 선택", "相談希望旅行会社を選択", { undecided: true }),
  item("honeymoon-flight", "honeymoon", "항공 개별 진행 여부 결정", "航空券を個別手配するか決定", { undecided: true }),
  item("honeymoon-email", "honeymoon", "견적 받을 이메일 준비", "見積受信用メールを準備"),
  item("honeymoon-consult-info", "honeymoon", "상담 신청 정보 정리", "相談申込情報を整理"),

  item("parents-makeup", "parents", "혼주 메이크업 안내 필요 여부 확인", "両家親メイク案内の必要有無を確認", { undecided: true }),
  item("parents-attire", "parents", "혼주 의상 일정 확인", "両家親衣装日程を確認", { undecided: true }),
  item("parents-transport", "parents", "혼주 이동 동선 확인", "両家親の移動動線を確認", { deadline: "2026-11-20" }),

  item("invitation-card", "invitation", "청첩장 제작 및 발송 일정 확정", "招待状制作・発送日程を確定", { deadline: "2026-10-31", undecided: true }),
  item("invitation-bouquet", "invitation", "부케 업체 및 색감 결정", "ブーケ業者と色味を決定", { deadline: "2026-11-15" }),
  item("invitation-mc", "invitation", "사회자 섭외 및 진행안 공유", "司会者手配と進行案共有", { deadline: "2026-11-15", undecided: true }),

  item("home-move-date", "home", "신혼집 입주 일정 확인", "新居入居日程を確認", { undecided: true }),
  item("home-appliance", "home", "가전 상담 예약", "家電相談を予約", { undecided: true }),
  item("home-furniture", "home", "가구 상담 예약", "家具相談を予約", { undecided: true }),
  item("home-bed", "home", "침대/매트리스 확인", "ベッド・マットレスを確認", { undecided: true }),
  item("home-internet", "home", "인터넷/IPTV 확인", "インターネット・IPTVを確認", { undecided: true }),
  item("home-rental", "home", "렌탈가전 확인", "レンタル家電を確認", { undecided: true }),
  item("home-cleaning", "home", "입주청소 확인", "入居清掃を確認", { undecided: true }),
  item("home-moving", "home", "이사 업체 확인", "引越し業者を確認", { undecided: true }),
  item("home-affiliate", "home", "플래너 통해 제휴 예약 필요 여부 확인", "プランナー経由の提携予約が必要か確認", { important: true }),

  item("payment-deposit", "payment", "계약금 30만원 확인", "契約金30万ウォンを確認", { important: true }),
  item("payment-middle", "payment", "중도금: 잔액의 80%, 웨딩촬영 30일 전 결제 확인", "中間金: 残額80%、撮影30日前支払いを確認", { deadline: "2026-05-15", important: true }),
  item("payment-final", "payment", "잔금: 본식 15일 전 결제 확인", "残金: 挙式15日前支払いを確認", { deadline: "2026-11-21", important: true }),
  item("payment-points", "payment", "포인트로 중도금/잔금 결제 가능 여부 확인", "ポイントで中間金・残金支払い可能か確認", { undecided: true }),
  item("payment-secret-discount", "payment", "시크릿 할인 항목 확인", "シークレット割引項目を確認"),
  item("payment-may-voucher", "payment", "5월 한정 바우처 확인", "5月限定バウチャーを確認"),
  item("payment-required-extra", "payment", "필수 별도비용 확인", "必須追加費用を確認", { important: true }),
  item("payment-fitting-fee", "payment", "드레스투어 피팅비 확인", "ドレスツアーフィッティング費を確認"),
  item("payment-photo-helper", "payment", "촬영헬퍼비 확인", "撮影ヘルパー費を確認", { deadline: "2026-06-13" }),
  item("payment-ceremony-helper", "payment", "본식헬퍼비 확인", "挙式ヘルパー費を確認", { deadline: "2026-12-05" }),
  item("payment-designer-artist", "payment", "디자이너/작가 지정비 확인", "デザイナー・作家指定料を確認"),
  item("points-site", "payment", "포인트 사이트 가입", "ポイントサイトに登録"),
  item("points-supporter", "payment", "서포터즈 등업", "サポーターズ等級アップ"),
  item("points-guidebook", "payment", "포인트 가이드북 확인", "ポイントガイドブックを確認"),
  item("points-apply", "payment", "포인트 적립 신청 방법 확인", "ポイント積立申請方法を確認"),
  item("points-fair", "payment", "박람회 방문 포인트 신청", "フェア訪問ポイントを申請"),
  item("points-consult", "payment", "업체 상담 포인트 신청", "業者相談ポイントを申請"),
  item("points-review", "payment", "후기 포인트 신청", "レビュー投稿ポイントを申請"),
  item("points-planner-praise", "payment", "담당 플래너 칭찬글 포인트 신청", "担当プランナー称賛文ポイントを申請"),
  item("points-cashback-manual", "payment", "캐시백은 자동 적립이 아니라 직접 신청해야 함을 표시", "キャッシュバックは自動ではなく直接申請が必要と表示", { important: true }),

  item("caution-photo-cancel-date", "caution", "촬영 변경/취소 가능 기한 확인", "撮影変更・取消可能期限を確認", { caution: true, important: true }),
  item("caution-celeb-cancel", "caution", "셀럽비비 촬영 취소 위약금 확인", "Celeb Bibi撮影取消キャンセル料を確認", { caution: true, important: true }),
  item("caution-photo-change", "caution", "촬영 일정 변경 위약금 확인", "撮影日程変更キャンセル料を確認", { caution: true }),
  item("caution-dress-tour", "caution", "드레스 투어 위약금 기간 확인", "ドレスツアーのキャンセル料期間を確認", { caution: true }),
  item("caution-snap-dvd", "caution", "스튜디오/본식스냅/DVD 위약금 기간 확인", "スタジオ・挙式スナップ・DVDのキャンセル料期間を確認", { caution: true }),
  item("caution-makeup", "caution", "메이크업 위약금 기간 확인", "メイクアップのキャンセル料期間を確認", { caution: true }),
  item("caution-props", "caution", "웨딩소품 위약금 기간 확인", "ウェディング小物のキャンセル料期間を確認", { caution: true }),
  item("caution-planner-before", "caution", "예약/변경/취소는 위약금 기간 전에 플래너에게 미리 문의", "予約・変更・取消はキャンセル料期間前にプランナーへ事前確認", { caution: true, important: true }),
  item("caution-card-direct", "caution", "카드결제는 다이렉트 방문 시만 가능", "カード決済はダイレクト訪問時のみ可能", { caution: true }),
  item("caution-affiliate-booking", "caution", "제휴업체는 플래너를 통해 예약해야 혜택 누락 방지", "提携業者はプランナー経由予約で特典漏れを防止", { caution: true, important: true }),

  item("planner-hair-change", "planner", "촬영 헤어변형을 스튜디오에서 추가할지 결정", "撮影ヘアチェンジをスタジオで追加するか決定", { undecided: true }),
  item("planner-snap", "planner", "본식 스냅 제휴업체 안내 필요 여부", "挙式スナップ提携業者案内の必要有無", { undecided: true }),
  item("planner-dvd", "planner", "본식 DVD 제휴업체 안내 필요 여부", "挙式DVD提携業者案内の必要有無", { undecided: true }),
  item("planner-parent-makeup", "planner", "혼주 메이크업 안내 필요 여부", "両家親メイク案内の必要有無", { undecided: true }),
  item("planner-parent-hanbok", "planner", "혼주 한복 안내 필요 여부", "両家親韓服案内の必要有無", { undecided: true }),
  item("planner-attire-jewelry", "planner", "예복/예물 제휴사 안내 필요 여부", "礼服・指輪提携先案内の必要有無", { undecided: true }),
  item("planner-honeymoon", "planner", "허니문 제휴 여행사 안내 필요 여부", "ハネムーン提携旅行会社案内の必要有無", { undecided: true }),
  item("planner-home", "planner", "신혼집 가전/가구 제휴 상담 필요 여부", "新居家電・家具提携相談の必要有無", { undecided: true }),
];

const budget: BudgetItem[] = [
  { id: "pkg-celeb-selene-hiel", category: "package", title: lt("셀럽비비 토탈 + 셀레네 1회 + 히엘 원장급 1회", "Celeb Bibi Total + Selene 1回 + Hiel院長級1回"), amount: 2200000 },
  { id: "pkg-celeb-kenneth-hiel", category: "package", title: lt("셀럽비비 토탈 + 더케네스블랑 1회 + 히엘 원장급 1회", "Celeb Bibi Total + The Kenneth Blanc 1回 + Hiel院長級1回"), amount: 2300000 },
  { id: "pkg-celeb-jsp-hiel", category: "package", title: lt("셀럽비비 토탈 + 제이스포사 1회 + 히엘 원장급 1회", "Celeb Bibi Total + J Sposa 1回 + Hiel院長級1回"), amount: 2430000 },
  { id: "required-original-edit", category: "required", title: lt("원본+수정본", "原本＋修正版"), amount: 440000, required: true, dueDate: "2026-06-14" },
  { id: "required-dress-fitting", category: "required", title: lt("드레스투어 피팅비", "ドレスツアーフィッティング費"), amount: 55000, amountLabel: lt("샵당 5.5만원", "1店あたり5.5万ウォン"), required: true },
  { id: "required-photo-helper", category: "required", title: lt("촬영헬퍼비", "撮影ヘルパー費"), amount: 250000, amountLabel: lt("기본 25만원 이상", "基本25万ウォン以上"), required: true, dueDate: "2026-06-14" },
  { id: "required-ceremony-helper", category: "required", title: lt("본식헬퍼비", "挙式ヘルパー費"), amount: 250000, amountLabel: lt("기본 25만원 이상", "基本25万ウォン以上"), required: true, dueDate: "2026-12-06" },
  { id: "required-designer", category: "required", title: lt("담당 디자이너 지정비", "担当デザイナー指定料"), amount: 55000 },
  { id: "required-artist", category: "required", title: lt("작가 지정비", "作家指定料"), amountLabel: lt("대표 55만원, 이사 33만원, 그 외 22만원", "代表55万、理事33万、その他22万ウォン") },
  { id: "optional-email-select", category: "optional", title: lt("이메일 셀렉 추가", "メールセレクト追加"), amount: 110000 },
  { id: "optional-priority-edit", category: "optional", title: lt("선수정본 5컷", "先行修正5カット"), amount: 55000 },
  { id: "optional-sunset", category: "optional", title: lt("노을씬", "夕焼けシーン"), amount: 110000 },
  { id: "optional-bus-stop", category: "optional", title: lt("버스정류장씬", "バス停シーン"), amount: 110000 },
  { id: "optional-bike", category: "optional", title: lt("야외 자전거씬", "屋外自転車シーン"), amount: 110000 },
  { id: "optional-hanbok-photo", category: "optional", title: lt("한복의상 촬영 추가", "韓服衣装撮影追加"), amount: 110000 },
  { id: "optional-bride-hair-2", category: "optional", title: lt("스튜디오 내 헤어변형 신부 2회", "スタジオ内新婦ヘアチェンジ2回"), amount: 220000 },
  { id: "optional-bride-hair-3", category: "optional", title: lt("스튜디오 내 헤어변형 신부 3회", "スタジオ内新婦ヘアチェンジ3回"), amount: 330000 },
  { id: "optional-groom-hair", category: "optional", title: lt("신랑 헤어변형 1회 추가", "新郎ヘアチェンジ1回追加"), amount: 55000 },
  { id: "optional-external-hair-room", category: "optional", title: lt("외부 헤어 출장 룸 사용료", "外部ヘア出張ルーム使用料"), amount: 55000 },
  { id: "discount-secret", category: "discount", title: lt("시크릿 할인", "シークレット割引"), amount: -50000, amountLabel: lt("해당 업체 품목당 5만원 할인", "対象業者品目ごとに5万ウォン割引") },
  { id: "discount-may-voucher", category: "discount", title: lt("5월 한정 바우처", "5月限定バウチャー"), amount: -100000, amountLabel: lt("10만원 할인권", "10万ウォン割引券") },
  { id: "benefit-premium-dress", category: "discount", title: lt("셀럽비비 프리미엄 드레스 1벌 무료 업그레이드", "Celeb Bibiプレミアムドレス1着無料アップグレード") },
  { id: "benefit-morning-scene", category: "discount", title: lt("오전 촬영자 버스정류장씬 또는 자전거씬 중 서비스 택1", "午前撮影者はバス停または自転車シーンからサービス1つ選択") },
  { id: "benefit-makeup-upgrade", category: "discount", title: lt("김활란뮤제네프 실장금액으로 부원장 무료 업그레이드 가능", "Kim Hwallan Musee Neuf 室長料金で副院長へ無料アップグレード可能") },
];

const schedule: ScheduleItem[] = [
  { id: "schedule-photo-prep", type: "photo", title: lt("촬영 헤어메이크업/촬영가봉", "撮影ヘアメイク・仮縫い"), startsAt: "2026-06-14T12:00:00+09:00", endsAt: "2026-06-14T14:30:00+09:00", location: lt("셀럽비비 토탈", "Celeb Bibi Total") },
  { id: "schedule-photo", type: "photo", title: lt("웨딩촬영", "前撮り"), startsAt: "2026-06-14T14:30:00+09:00", location: lt("셀럽비비 토탈", "Celeb Bibi Total") },
  { id: "schedule-wedding", type: "ceremony", title: lt("예식", "挙式"), startsAt: "2026-12-06T13:00:00+09:00", location: lt("스탠포드호텔코리아", "スタンフォードホテルコリア") },
  { id: "schedule-middle-payment", type: "payment", title: lt("중도금 결제", "中間金支払い"), startsAt: "2026-05-15T10:00:00+09:00", relatedChecklistId: "payment-middle" },
  { id: "schedule-final-payment", type: "payment", title: lt("잔금 결제", "残金支払い"), startsAt: "2026-11-21T10:00:00+09:00", relatedChecklistId: "payment-final" },
  { id: "schedule-photo-check", type: "deadline", title: lt("촬영 준비 최종 확인", "撮影準備最終確認"), startsAt: "2026-06-07T10:00:00+09:00" },
  { id: "schedule-wedding-check", type: "deadline", title: lt("본식 준비 최종 확인", "挙式準備最終確認"), startsAt: "2026-11-29T10:00:00+09:00" },
];

export const defaultWeddingData: WeddingData = {
  profile: {
    groomName: lt("정동균", "チョン・ドンギュン"),
    brideName: lt("야마다 츠키나", "山田月菜"),
    weddingDateTime: "2026-12-06T13:00:00+09:00",
    weddingVenue: lt("스탠포드호텔코리아", "スタンフォードホテルコリア"),
    photoDateTime: "2026-06-14T14:30:00+09:00",
    photoPrepDateTime: "2026-06-14T12:00:00+09:00",
    photoPrepEndDateTime: "2026-06-14T14:30:00+09:00",
    photoVendor: lt("셀럽비비 토탈", "Celeb Bibi Total"),
  },
  language: "ko",
  template: {
    version: 1,
    categories,
    checklist,
    budget,
    schedule,
  },
  userState: {
    checklist: {},
    budget: {
      "pkg-celeb-selene-hiel": { paid: false, selected: true },
    },
    notes: {},
  },
  updatedAt: "2026-05-27T00:00:00+09:00",
};
